package mybatis.pojo;

public class Author {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.username
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    private Integer username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.username
     *
     * @return the value of author.username
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    public Integer getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.username
     *
     * @param username the value for author.username
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    public void setUsername(Integer username) {
        this.username = username;
    }
}