package mybatis.pojo;

public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.id
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.title
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.author_id
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    private Integer authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.state
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.featured
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    private Byte featured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.style
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    private String style;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.id
     *
     * @return the value of blog.id
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.id
     *
     * @param id the value for blog.id
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.title
     *
     * @return the value of blog.title
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.title
     *
     * @param title the value for blog.title
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.author_id
     *
     * @return the value of blog.author_id
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.author_id
     *
     * @param authorId the value for blog.author_id
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.state
     *
     * @return the value of blog.state
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.state
     *
     * @param state the value for blog.state
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.featured
     *
     * @return the value of blog.featured
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    public Byte getFeatured() {
        return featured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.featured
     *
     * @param featured the value for blog.featured
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    public void setFeatured(Byte featured) {
        this.featured = featured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.style
     *
     * @return the value of blog.style
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.style
     *
     * @param style the value for blog.style
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }
}