package mybatis.mapper;

import java.util.List;
import mybatis.pojo.Author;
import mybatis.pojo.AuthorExample;
import org.apache.ibatis.annotations.Param;

public interface AuthorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    long countByExample(AuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    int deleteByExample(AuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    int deleteByPrimaryKey(Integer username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    int insert(Author record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    int insertSelective(Author record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    List<Author> selectByExample(AuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    int updateByExampleSelective(@Param("record") Author record, @Param("example") AuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Tue May 05 12:46:23 EDT 2020
     */
    int updateByExample(@Param("record") Author record, @Param("example") AuthorExample example);
}